apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'example-action'
description: 'Trigger pipelines or procedures in a CD/RO instance. This does not wait for the job to complete, it will trigger and then return the response from CD/RO'
inputs:
  url:
    description: 'The URL for the CD/RO server'
    required: true
outputs:
  response:
    value: ${{ steps.example.outputs.output1 }}
    description: 'The example output'
runs:
  using: composite
  steps:
    - name: Example of doing things
      id: example
      uses: docker://public.ecr.aws/r1n1q0e5/gradinsky/example-action:latest
      with:
        entrypoint: example-action
        args: --url "${{ inputs.url }}"
